"""add_neon_auth_user_id_to_users

Revision ID: a73936ff25f9
Revises: 4049cc78c8f1
Create Date: 2025-07-07 20:00:20.456954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73936ff25f9'
down_revision: Union[str, Sequence[str], None] = '4049cc78c8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('neon_auth_user_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['neon_auth_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'neon_auth_user_id')
    # ### end Alembic commands ###
