name: Deployment Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Change to frontend directory
      run: cd frontend
      
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Generate types
      run: |
        cd frontend
        npm run generate-types
        
    - name: TypeScript check
      run: |
        cd frontend
        npx tsc --noEmit --skipLibCheck
        
    - name: Run linter
      run: |
        cd frontend
        npm run lint
      continue-on-error: true  # Don't fail build on lint errors
      
    - name: Test production build
      run: |
        cd frontend
        npm run build
        
    - name: Run tests
      run: |
        cd frontend
        npm run test --run
      continue-on-error: true  # Don't fail build on test failures
      
    - name: Check bundle size
      run: |
        cd frontend
        echo "Build size:" && du -sh dist
        echo "Large files (>1MB):"
        find dist -size +1M -exec ls -lh {} \; || echo "No large files found"
        
    - name: Deployment ready ✅
      run: echo "All checks passed! Ready for deployment 🚀"